"
This package includes the needed logic to handle certificates and certificate stores in OpenSSL.

It has implemented:

  - Support to X509 certificates and stores.
  - Accessing to OSX root certificate and load them in OpenSSL.
  - Accessing to Windows certificates and load them in OpenSSL.
"
Class {
	#name : #ManifestZodiacOpenSSLCertificates,
	#superclass : #PackageManifest,
	#category : #'Zodiac-OpenSSL-Certificates-Base'
}
